---
- name: config tomcat10
  hosts: all
  tasks:
    - name: install tomcat10
      apt:
        name: tomcat10
        state: present
        update_cache: yes
    - name: install tomcat10-admin
      apt:
        name: tomcat10-admin
        state: present
        update_cache: yes
    - name: copy tomcat-users.xml file
      copy:
        src: tomcat-users.xml
        dest: /etc/tomcat10
    - name: change port from 8080 to 9090
      replace:
        regexp: 8080
        replace: 9090
        path: /etc/tomcat10/server.xml
    - name: pause the minute
      pause:
        minutes: 1
    - name: restart the tomcat services
      service:
        name: tomcat10
        state: restarted
    - name: check the url of server 1
      uri:
        url: http://172.31.37.81
        status_code: 200
    - name: check the url of server 2
      uri:
        url: http://172.31.34.252
        status_code: 200

